### PR TITLE
Changed has relation method

### PR DESCRIPTION
**Pull request by execut**
Hello! I changed exist relation detection method for possibility use dynamic relations defined in model

### CODE REVIEW

**Comment by juban** [comment]
Hi,

Could you elaborate a bit more please?
What are you trying to achieve and what do you mean by "dynamic relations defined in model"?

Thanks.

**Comment by execut** [comment]
I mean the cases when the relationships in the model are defined not through getters, but through the override of the getRelation method. I think this approach is simply more flexible and allows don't write methods-stubs in this cases

**Comment by execut** [comment]
Merged and fixed compatibility with new version.

**Comment by juban** [comment]
Your feature has been merged to master.

**Pull request closed without merging**
