### PR TITLE
Check Interface instead of Class

### PR DESCRIPTION
**Pull request by bookin**
> Only pure Active Record API is used so it should work with any DB driver

### CODE REVIEW

**Comment by bookin** [comment]
for example I can't use ActiveQuery from mongodb (yii\mongodb\ActiveQuery), but this class implements same interface

**Comment by bookin** [comment]
Same problem with `yii\db\ActiveRecord`, cannot use `yii\mongodb\ActiveRecord`, but if change all `yii\db\ActiveRecord` to `yii\db\BaseActiveRecord` all is works.

**Comment by juban** [comment]
Thanks. Seems smart. I will check that ASAP and let you know.

**Comment by bookin** [comment]
Thanks, will be wait.

**Comment by juban** [comment]
I have pushed the changes to master.
Could-you check that's working for you please?
Thanks.

**Comment by bookin** [comment]
Seems like ok, no any errors or problems, thanks.

**Comment by juban** [comment]
Nice! Thanks a lot for your contribution and tests.
I will release version 1.2.0 shortly.

**Pull request merged**
